/* Generated by scripts/bake-filament-shell-textures.ts. */
import { useMemo } from "react";
import { useBuffer } from "react-native-filament";

import type { BallId } from "./ballCatalog";

type FilamentBuffer = Exclude<ReturnType<typeof useBuffer>, undefined>;

export const BALL_FILAMENT_TEXTURE_SOURCES: Record<BallId, number> = {
  poke: require("../../../../assets/models/shells/poke.png"),
  great: require("../../../../assets/models/shells/great.png"),
  ultra: require("../../../../assets/models/shells/ultra.png"),
  premier: require("../../../../assets/models/shells/premier.png"),
  repeat: require("../../../../assets/models/shells/repeat.png"),
  timer: require("../../../../assets/models/shells/timer.png"),
  nest: require("../../../../assets/models/shells/nest.png"),
  net: require("../../../../assets/models/shells/net.png"),
  dive: require("../../../../assets/models/shells/dive.png"),
  heal: require("../../../../assets/models/shells/heal.png"),
  quick: require("../../../../assets/models/shells/quick.png"),
  dusk: require("../../../../assets/models/shells/dusk.png"),
  luxury: require("../../../../assets/models/shells/luxury.png"),
  master: require("../../../../assets/models/shells/master.png"),
  safari: require("../../../../assets/models/shells/safari.png"),
  level: require("../../../../assets/models/shells/level.png"),
  lure: require("../../../../assets/models/shells/lure.png"),
  moon: require("../../../../assets/models/shells/moon.png"),
  friend: require("../../../../assets/models/shells/friend.png"),
  love: require("../../../../assets/models/shells/love.png"),
  heavy: require("../../../../assets/models/shells/heavy.png"),
  fast: require("../../../../assets/models/shells/fast.png"),
  sport: require("../../../../assets/models/shells/sport.png"),
  dream: require("../../../../assets/models/shells/dream.png"),
  beast: require("../../../../assets/models/shells/beast.png"),
  cherish: require("../../../../assets/models/shells/cherish.png"),
};

export function useBallFilamentTextures(): Partial<Record<BallId, FilamentBuffer>> {
  const poke = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.poke });
  const great = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.great });
  const ultra = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.ultra });
  const premier = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.premier });
  const repeat = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.repeat });
  const timer = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.timer });
  const nest = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.nest });
  const net = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.net });
  const dive = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.dive });
  const heal = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.heal });
  const quick = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.quick });
  const dusk = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.dusk });
  const luxury = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.luxury });
  const master = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.master });
  const safari = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.safari });
  const level = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.level });
  const lure = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.lure });
  const moon = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.moon });
  const friend = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.friend });
  const love = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.love });
  const heavy = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.heavy });
  const fast = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.fast });
  const sport = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.sport });
  const dream = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.dream });
  const beast = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.beast });
  const cherish = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.cherish });

  return useMemo(
    () => ({
      poke,
      great,
      ultra,
      premier,
      repeat,
      timer,
      nest,
      net,
      dive,
      heal,
      quick,
      dusk,
      luxury,
      master,
      safari,
      level,
      lure,
      moon,
      friend,
      love,
      heavy,
      fast,
      sport,
      dream,
      beast,
      cherish,
    }),
    [
      poke,
      great,
      ultra,
      premier,
      repeat,
      timer,
      nest,
      net,
      dive,
      heal,
      quick,
      dusk,
      luxury,
      master,
      safari,
      level,
      lure,
      moon,
      friend,
      love,
      heavy,
      fast,
      sport,
      dream,
      beast,
      cherish,
    ]
  );
}
