import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { deflateSync } from "node:zlib";

import { format } from "prettier";

import { BALL_CATALOG } from "../src/components/poc/capture/ballCatalog";
import type { BallId } from "../src/components/poc/capture/ballCatalog";
import {
  FILAMENT_SHELL_TEXTURE_SIZE,
  filamentShellMaskCoverage,
  filamentSurface,
} from "../src/components/poc/capture/ballFilamentSurface";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(scriptDirectory, "..");
const textureDirectory = resolve(projectRoot, "assets/models/shells");
const generatedSourcePath = resolve(
  projectRoot,
  "src/components/poc/capture/ballFilamentTextures.generated.ts"
);
const ballIds = Object.keys(BALL_CATALOG) as BallId[];

function decodeSrgb(channel: number): number {
  const value = channel / 255;
  return value <= 0.04045 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4;
}

function encodeSrgb(channel: number): number {
  const value = channel <= 0.0031308 ? channel * 12.92 : 1.055 * channel ** (1 / 2.4) - 0.055;
  return Math.round(Math.max(0, Math.min(1, value)) * 255);
}

function hexToLinear(hex: string): [number, number, number] {
  const value = Number.parseInt(hex.slice(1), 16);
  return [decodeSrgb((value >> 16) & 255), decodeSrgb((value >> 8) & 255), decodeSrgb(value & 255)];
}

const crcTable = Array.from({ length: 256 }, (_, index) => {
  let value = index;
  for (let bit = 0; bit < 8; bit += 1) {
    value = (value & 1) === 1 ? 0xedb88320 ^ (value >>> 1) : value >>> 1;
  }
  return value >>> 0;
});

function crc32(bytes: Buffer): number {
  let crc = 0xffffffff;
  for (const byte of bytes) crc = crcTable[(crc ^ byte) & 0xff]! ^ (crc >>> 8);
  return (crc ^ 0xffffffff) >>> 0;
}

function pngChunk(type: string, data: Buffer): Buffer {
  const typeBuffer = Buffer.from(type, "ascii");
  const header = Buffer.alloc(4);
  header.writeUInt32BE(data.length, 0);
  const checksum = Buffer.alloc(4);
  checksum.writeUInt32BE(crc32(Buffer.concat([typeBuffer, data])), 0);
  return Buffer.concat([header, typeBuffer, data, checksum]);
}

function encodeRgbaPng(width: number, height: number, pixels: Buffer): Buffer {
  const rows = Buffer.alloc(height * (1 + width * 4));
  for (let y = 0; y < height; y += 1) {
    const target = y * (1 + width * 4);
    rows[target] = 0;
    pixels.copy(rows, target + 1, y * width * 4, (y + 1) * width * 4);
  }

  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(width, 0);
  ihdr.writeUInt32BE(height, 4);
  ihdr[8] = 8;
  ihdr[9] = 6;
  return Buffer.concat([
    Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]),
    pngChunk("IHDR", ihdr),
    pngChunk("IDAT", deflateSync(rows, { level: 9 })),
    pngChunk("IEND", Buffer.alloc(0)),
  ]);
}

function shellTexture(ballId: BallId): Buffer {
  const { height, width } = FILAMENT_SHELL_TEXTURE_SIZE;
  const surface = filamentSurface(ballId);
  const base = hexToLinear(surface.base);
  const accent = hexToLinear(surface.accent);
  const pixels = Buffer.alloc(width * height * 4);

  for (let y = 0; y < height; y += 1) {
    const v = 1 - y / (height - 1);
    for (let x = 0; x < width; x += 1) {
      const u = x / (width - 1);
      const coverage = filamentShellMaskCoverage(surface.art, u, v);
      const offset = (y * width + x) * 4;
      pixels[offset] = encodeSrgb(base[0] + (accent[0] - base[0]) * coverage);
      pixels[offset + 1] = encodeSrgb(base[1] + (accent[1] - base[1]) * coverage);
      pixels[offset + 2] = encodeSrgb(base[2] + (accent[2] - base[2]) * coverage);
      pixels[offset + 3] = 255;
    }
  }

  return encodeRgbaPng(width, height, pixels);
}

await mkdir(textureDirectory, { recursive: true });
await Promise.all(
  ballIds.map((ballId) =>
    writeFile(resolve(textureDirectory, `${ballId}.png`), shellTexture(ballId))
  )
);

const generated = `/* Generated by scripts/bake-filament-shell-textures.ts. */
import { useMemo } from "react";
import { useBuffer } from "react-native-filament";

import type { BallId } from "./ballCatalog";

type FilamentBuffer = Exclude<ReturnType<typeof useBuffer>, undefined>;

export const BALL_FILAMENT_TEXTURE_SOURCES: Record<BallId, number> = {
${ballIds.map((ballId) => `  ${ballId}: require("../../../../assets/models/shells/${ballId}.png"),`).join("\n")}
};

export function useBallFilamentTextures(): Partial<Record<BallId, FilamentBuffer>> {
${ballIds.map((ballId) => `  const ${ballId} = useBuffer({ source: BALL_FILAMENT_TEXTURE_SOURCES.${ballId} });`).join("\n")}

  return useMemo(
    () => ({ ${ballIds.join(", ")} }),
    [${ballIds.join(", ")}]
  );
}
`;
await writeFile(
  generatedSourcePath,
  await format(generated, { parser: "typescript", printWidth: 100, trailingComma: "es5" })
);
console.log(`Baked ${ballIds.length} Filament shell textures → ${textureDirectory}`);
